# version: '3'
# services:
#   db:
#     image: postgres:15
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=travel_db
#     ports:
#       - '5454:5432'
#     volumes: 
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

version: '3'
services:
  api:
    image: chocolatedream/react-server:latest
    depends_on:
      - db
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wines
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: